/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DrawingWho
 */
export interface DrawingWho {
    /**
     * 
     * @type {string}
     * @memberof DrawingWho
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DrawingWho
     */
    name?: string;
}

/**
 * Check if a given object implements the DrawingWho interface.
 */
export function instanceOfDrawingWho(value: object): value is DrawingWho {
    return true;
}

export function DrawingWhoFromJSON(json: any): DrawingWho {
    return DrawingWhoFromJSONTyped(json, false);
}

export function DrawingWhoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawingWho {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'] == null ? undefined : json['_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DrawingWhoToJSON(value?: DrawingWho | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '_id': value['id'],
        'name': value['name'],
    };
}

