/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdMembersUserIdPatchRequest
 */
export interface GroupsGroupIdMembersUserIdPatchRequest {
    /**
     * 
     * @type {boolean}
     * @memberof GroupsGroupIdMembersUserIdPatchRequest
     */
    isOwner: boolean;
}

/**
 * Check if a given object implements the GroupsGroupIdMembersUserIdPatchRequest interface.
 */
export function instanceOfGroupsGroupIdMembersUserIdPatchRequest(value: object): value is GroupsGroupIdMembersUserIdPatchRequest {
    if (!('isOwner' in value) || value['isOwner'] === undefined) return false;
    return true;
}

export function GroupsGroupIdMembersUserIdPatchRequestFromJSON(json: any): GroupsGroupIdMembersUserIdPatchRequest {
    return GroupsGroupIdMembersUserIdPatchRequestFromJSONTyped(json, false);
}

export function GroupsGroupIdMembersUserIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdMembersUserIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isOwner': json['isOwner'],
    };
}

export function GroupsGroupIdMembersUserIdPatchRequestToJSON(value?: GroupsGroupIdMembersUserIdPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isOwner': value['isOwner'],
    };
}

