/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupMember
 */
export interface GroupMember {
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    avatar?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GroupMember
     */
    emailNotification: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupMember
     */
    pushTokens?: Array<string>;
}

/**
 * Check if a given object implements the GroupMember interface.
 */
export function instanceOfGroupMember(value: object): value is GroupMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('emailNotification' in value) || value['emailNotification'] === undefined) return false;
    return true;
}

export function GroupMemberFromJSON(json: any): GroupMember {
    return GroupMemberFromJSONTyped(json, false);
}

export function GroupMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'name': json['name'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'emailNotification': json['emailNotification'],
        'pushTokens': json['pushTokens'] == null ? undefined : json['pushTokens'],
    };
}

export function GroupMemberToJSON(value?: GroupMember | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '_id': value['id'],
        'name': value['name'],
        'avatar': value['avatar'],
        'emailNotification': value['emailNotification'],
        'pushTokens': value['pushTokens'],
    };
}

