/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdDrawingsPost200Response
 */
export interface GroupsGroupIdDrawingsPost200Response {
    /**
     * 
     * @type {number}
     * @memberof GroupsGroupIdDrawingsPost200Response
     */
    seconds: number;
    /**
     * 
     * @type {boolean}
     * @memberof GroupsGroupIdDrawingsPost200Response
     */
    self: boolean;
}

/**
 * Check if a given object implements the GroupsGroupIdDrawingsPost200Response interface.
 */
export function instanceOfGroupsGroupIdDrawingsPost200Response(value: object): value is GroupsGroupIdDrawingsPost200Response {
    if (!('seconds' in value) || value['seconds'] === undefined) return false;
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function GroupsGroupIdDrawingsPost200ResponseFromJSON(json: any): GroupsGroupIdDrawingsPost200Response {
    return GroupsGroupIdDrawingsPost200ResponseFromJSONTyped(json, false);
}

export function GroupsGroupIdDrawingsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdDrawingsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'seconds': json['seconds'],
        'self': json['self'],
    };
}

export function GroupsGroupIdDrawingsPost200ResponseToJSON(value?: GroupsGroupIdDrawingsPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'seconds': value['seconds'],
        'self': value['self'],
    };
}

