/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdDrawingsPostRequest
 */
export interface GroupsGroupIdDrawingsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof GroupsGroupIdDrawingsPostRequest
     */
    seconds: number;
    /**
     * 
     * @type {boolean}
     * @memberof GroupsGroupIdDrawingsPostRequest
     */
    self: boolean;
}

/**
 * Check if a given object implements the GroupsGroupIdDrawingsPostRequest interface.
 */
export function instanceOfGroupsGroupIdDrawingsPostRequest(value: object): value is GroupsGroupIdDrawingsPostRequest {
    if (!('seconds' in value) || value['seconds'] === undefined) return false;
    if (!('self' in value) || value['self'] === undefined) return false;
    return true;
}

export function GroupsGroupIdDrawingsPostRequestFromJSON(json: any): GroupsGroupIdDrawingsPostRequest {
    return GroupsGroupIdDrawingsPostRequestFromJSONTyped(json, false);
}

export function GroupsGroupIdDrawingsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdDrawingsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'seconds': json['seconds'],
        'self': json['self'],
    };
}

export function GroupsGroupIdDrawingsPostRequestToJSON(value?: GroupsGroupIdDrawingsPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'seconds': value['seconds'],
        'self': value['self'],
    };
}

