/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdDrawingsDrawingIdPostRequest
 */
export interface GroupsGroupIdDrawingsDrawingIdPostRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdDrawingsDrawingIdPostRequest
     */
    drink: string;
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdDrawingsDrawingIdPostRequest
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdDrawingsDrawingIdPostRequest
     */
    extras?: string;
}

/**
 * Check if a given object implements the GroupsGroupIdDrawingsDrawingIdPostRequest interface.
 */
export function instanceOfGroupsGroupIdDrawingsDrawingIdPostRequest(value: object): value is GroupsGroupIdDrawingsDrawingIdPostRequest {
    if (!('drink' in value) || value['drink'] === undefined) return false;
    return true;
}

export function GroupsGroupIdDrawingsDrawingIdPostRequestFromJSON(json: any): GroupsGroupIdDrawingsDrawingIdPostRequest {
    return GroupsGroupIdDrawingsDrawingIdPostRequestFromJSONTyped(json, false);
}

export function GroupsGroupIdDrawingsDrawingIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdDrawingsDrawingIdPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'drink': json['drink'],
        'text': json['text'] == null ? undefined : json['text'],
        'extras': json['extras'] == null ? undefined : json['extras'],
    };
}

export function GroupsGroupIdDrawingsDrawingIdPostRequestToJSON(value?: GroupsGroupIdDrawingsDrawingIdPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'drink': value['drink'],
        'text': value['text'],
        'extras': value['extras'],
    };
}

