/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdMembersPostRequest
 */
export interface GroupsGroupIdMembersPostRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdMembersPostRequest
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof GroupsGroupIdMembersPostRequest
     */
    invite: boolean;
}

/**
 * Check if a given object implements the GroupsGroupIdMembersPostRequest interface.
 */
export function instanceOfGroupsGroupIdMembersPostRequest(value: object): value is GroupsGroupIdMembersPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('invite' in value) || value['invite'] === undefined) return false;
    return true;
}

export function GroupsGroupIdMembersPostRequestFromJSON(json: any): GroupsGroupIdMembersPostRequest {
    return GroupsGroupIdMembersPostRequestFromJSONTyped(json, false);
}

export function GroupsGroupIdMembersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdMembersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'invite': json['invite'],
    };
}

export function GroupsGroupIdMembersPostRequestToJSON(value?: GroupsGroupIdMembersPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'invite': value['invite'],
    };
}

