/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdDrinksPostRequest
 */
export interface GroupsGroupIdDrinksPostRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdDrinksPostRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdDrinksPostRequest
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof GroupsGroupIdDrinksPostRequest
     */
    extras: string;
}

/**
 * Check if a given object implements the GroupsGroupIdDrinksPostRequest interface.
 */
export function instanceOfGroupsGroupIdDrinksPostRequest(value: object): value is GroupsGroupIdDrinksPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('extras' in value) || value['extras'] === undefined) return false;
    return true;
}

export function GroupsGroupIdDrinksPostRequestFromJSON(json: any): GroupsGroupIdDrinksPostRequest {
    return GroupsGroupIdDrinksPostRequestFromJSONTyped(json, false);
}

export function GroupsGroupIdDrinksPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdDrinksPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'icon': json['icon'],
        'extras': json['extras'],
    };
}

export function GroupsGroupIdDrinksPostRequestToJSON(value?: GroupsGroupIdDrinksPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'icon': value['icon'],
        'extras': value['extras'],
    };
}

