/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsGroupIdNotificationsPostRequest
 */
export interface GroupsGroupIdNotificationsPostRequest {
    /**
     * 
     * @type {boolean}
     * @memberof GroupsGroupIdNotificationsPostRequest
     */
    email: boolean;
}

/**
 * Check if a given object implements the GroupsGroupIdNotificationsPostRequest interface.
 */
export function instanceOfGroupsGroupIdNotificationsPostRequest(value: object): value is GroupsGroupIdNotificationsPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function GroupsGroupIdNotificationsPostRequestFromJSON(json: any): GroupsGroupIdNotificationsPostRequest {
    return GroupsGroupIdNotificationsPostRequestFromJSONTyped(json, false);
}

export function GroupsGroupIdNotificationsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsGroupIdNotificationsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function GroupsGroupIdNotificationsPostRequestToJSON(value?: GroupsGroupIdNotificationsPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

