/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupsPostRequest
 */
export interface GroupsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupsPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the GroupsPostRequest interface.
 */
export function instanceOfGroupsPostRequest(value: object): value is GroupsPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GroupsPostRequestFromJSON(json: any): GroupsPostRequest {
    return GroupsPostRequestFromJSONTyped(json, false);
}

export function GroupsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function GroupsPostRequestToJSON(value?: GroupsPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

