/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Invite
 */
export interface Invite {
    /**
     * 
     * @type {string}
     * @memberof Invite
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Invite
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Invite
     */
    date: string;
}

/**
 * Check if a given object implements the Invite interface.
 */
export function instanceOfInvite(value: object): value is Invite {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function InviteFromJSON(json: any): Invite {
    return InviteFromJSONTyped(json, false);
}

export function InviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invite {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'email': json['email'],
        'date': json['Date'],
    };
}

export function InviteToJSON(value?: Invite | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '_id': value['id'],
        'email': value['email'],
        'Date': value['date'],
    };
}

