/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberAdded
 */
export interface MemberAdded {
    /**
     * 
     * @type {string}
     * @memberof MemberAdded
     */
    message: MemberAddedMessageEnum;
}


/**
 * @export
 */
export const MemberAddedMessageEnum = {
    Ok: 'OK',
    NotMember: 'NOT_MEMBER',
    MaxMembers: 'MAX_MEMBERS'
} as const;
export type MemberAddedMessageEnum = typeof MemberAddedMessageEnum[keyof typeof MemberAddedMessageEnum];


/**
 * Check if a given object implements the MemberAdded interface.
 */
export function instanceOfMemberAdded(value: object): value is MemberAdded {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MemberAddedFromJSON(json: any): MemberAdded {
    return MemberAddedFromJSONTyped(json, false);
}

export function MemberAddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAdded {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function MemberAddedToJSON(value?: MemberAdded | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

