/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyInvite
 */
export interface MyInvite {
    /**
     * 
     * @type {string}
     * @memberof MyInvite
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof MyInvite
     */
    sendBy: string;
}

/**
 * Check if a given object implements the MyInvite interface.
 */
export function instanceOfMyInvite(value: object): value is MyInvite {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('sendBy' in value) || value['sendBy'] === undefined) return false;
    return true;
}

export function MyInviteFromJSON(json: any): MyInvite {
    return MyInviteFromJSONTyped(json, false);
}

export function MyInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyInvite {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'sendBy': json['sendBy'],
    };
}

export function MyInviteToJSON(value?: MyInvite | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'sendBy': value['sendBy'],
    };
}

