/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupMember } from './GroupMember';
import {
    GroupMemberFromJSON,
    GroupMemberFromJSONTyped,
    GroupMemberToJSON,
} from './GroupMember';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
} from './Profile';

/**
 * 
 * @export
 * @interface UsersGet200Response
 */
export interface UsersGet200Response {
    /**
     * 
     * @type {Profile}
     * @memberof UsersGet200Response
     */
    profile: Profile;
    /**
     * 
     * @type {Array<GroupMember>}
     * @memberof UsersGet200Response
     */
    groups: Array<GroupMember>;
}

/**
 * Check if a given object implements the UsersGet200Response interface.
 */
export function instanceOfUsersGet200Response(value: object): value is UsersGet200Response {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    return true;
}

export function UsersGet200ResponseFromJSON(json: any): UsersGet200Response {
    return UsersGet200ResponseFromJSONTyped(json, false);
}

export function UsersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ProfileFromJSON(json['profile']),
        'groups': ((json['groups'] as Array<any>).map(GroupMemberFromJSON)),
    };
}

export function UsersGet200ResponseToJSON(value?: UsersGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'profile': ProfileToJSON(value['profile']),
        'groups': ((value['groups'] as Array<any>).map(GroupMemberToJSON)),
    };
}

