/* tslint:disable */
/* eslint-disable */
/**
 * wiegaaterkoffiehalen OpenAPI
 * wiegaaterkoffiehalen OpenAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersPatchRequest
 */
export interface UsersPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersPatchRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPatchRequest
     */
    avatar: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPatchRequest
     */
    isInitSetup: boolean;
    /**
     * 
     * @type {number}
     * @memberof UsersPatchRequest
     */
    verificationCode?: number;
}

/**
 * Check if a given object implements the UsersPatchRequest interface.
 */
export function instanceOfUsersPatchRequest(value: object): value is UsersPatchRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('isInitSetup' in value) || value['isInitSetup'] === undefined) return false;
    return true;
}

export function UsersPatchRequestFromJSON(json: any): UsersPatchRequest {
    return UsersPatchRequestFromJSONTyped(json, false);
}

export function UsersPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'avatar': json['avatar'],
        'isInitSetup': json['isInitSetup'],
        'verificationCode': json['verificationCode'] == null ? undefined : json['verificationCode'],
    };
}

export function UsersPatchRequestToJSON(value?: UsersPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'avatar': value['avatar'],
        'isInitSetup': value['isInitSetup'],
        'verificationCode': value['verificationCode'],
    };
}

